name: 'Code sign a file'
description: 'Sign a file with a code signing certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate as a single base64, no header, footer or line breaks.'
    required: true
  password:
    description: 'The certificate password.'
    required: false
  folder:
    description: 'The folder that contains the files to sign, e.g. `target\release` or `.`.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
